FROM registry.access.redhat.com/ubi8/ubi:8.0

MAINTAINER Magnus K Karlsson <magnus.k.karlsson@domain.com>

ENV DOCROOT=/var/www/html

RUN yum install -y --nodocs --disableplugin subscription-manager httpd && \
  yum clean all -y --disableplugin subscription-manager && \
  echo "hello from parent" > ${DOCROOT}/index.html

ONBUILD COPY src/ ${DOCROOT}/

EXPOSE 80

RUN rm -rf /run/httpd && mkdir /run/httpd

USER root

CMD /usr/sbin/httpd -DFOREGROUND



