apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: quotes
    name: quotes
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: quotes
    name: quotes
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: quotes:latest
    runPolicy: Serial
    source:
      contextDir: quotes
      git:
        uri: https://github.com/magnuskkarlsson/DO288-apps/
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.4-ubi8
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: quotes
    name: quotes
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: quotes
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: quotes
        name: quotes
      spec:
        containers:
        - image: quotes:latest
          imagePullPolicy: IfNotPresent
          name: quotes
          ports:
          - containerPort: 8080
            protocol: TCP



