apiVersion: apps/v1
kind: Deployment
metadata:
  name: famous-quotes
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: famous-quotes
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
